[package]
name = "robert-rct"
version = "0.1.0"
authors = ["DennisMelamed <hal.melt1@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.4.0"
sha2 = "0.8.0"
rust-crypto = "0.2.36"
rand-mersenne-twister = { git = "https://github.com/KokaKiwi/rust-mersenne-twister" }
